In [24]:
# Question 1
# Write a Python program to convert an array to an ordinary list with the same items.

# Converting multi-dimensional NumPy Array to List

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy Array: ")
print(arr)

list1 = arr.tolist()
print(list1)

NumPy Array: 
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [2]:
# Question 2 
# Write a NumPy program to compute the sum of the diagonal elements of a given array.

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix:")
print(arr)
result = np.trace(arr)
print("The sum of the diagonals is:")
print(result)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The sum of the diagonals is:
15


In [14]:
# Question 3
# Given an array of your choice, get all the values higher than x
# if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.

import numpy as np
a = np.array([[1, 2], [3, 5]])
print("Original matrix: ")
print(a)
print("Values bigger than 2 =", a[a>2])

Original matrix: 
[[1 2]
 [3 5]]
Values bigger than 2 = [3 5]


In [15]:
#Question 4 
#Given two arrays, A & B have the same shape. 
#The task is to apply addition by hand: C is the new array.

import numpy as np
a = np.arange(9, dtype = int).reshape(3,3)

print('First array:' )
print(a)
print('\n')

print('Second array:' ) 
b = np.arange(2, 11, 1).reshape(3,3)
print(b)
print('\n')

print('Add the two arrays:')
c = np.add(a,b) 
print(c)

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Second array:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Add the two arrays:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [23]:
# Question 5
# Write a NumPy program to subtract the mean of each row of a given matrix.

import numpy as np
print("Original matrix:")
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(X)

print("\nSubtracting the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracting the mean of each row of the said matrix:

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
